app:
  name: "PyPluginizer"
  description: "A Plugin framework written in python"

  # Logger
  logger:
    level: "INFO"
    format: "%(asctime)s,%(msecs)03d %(levelname)-8s [%(filename)s:%(lineno)d] %(message)s"
    #format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
    #format: "[%(asctime)s] p%(process)s {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s','%m-%d %H:%M:%S')"

  # Core plugins
  core:
    directory: ./src/plugins/core

  # Users plugins
  users:
    directory: ./src/plugins/users

  # Hooks
  hooks:
    directory: ./src/hooks
